# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a4346129240d0849eef0e44fa8d9fdd8b8c04b627d46b4d74c4c19991203cd503ddf6fa664d6a1bc3e5b6f91ebfd9c436e689dc72da575bbb6c8f2922789a53

test:
  secret_key_base: 7b41aa8a38d9529ba6eaaa0d2becd3a5127ab8c1eb719c3a9577ac05f5ea5fbfc52d1ba24622a0f7346cb6fb1aa507a28e4e467f6dfecc4d52609194fc260526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
